In [1]:
import pandas

In [2]:
ds = pandas.read_csv('sal.csv')

In [3]:
ds.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
ds.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [6]:
x = ds['YearsExperience'].values.reshape(30,1)

In [7]:
type(x)

numpy.ndarray

In [8]:
x.shape

(30, 1)

In [9]:
y = ds['Salary']

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
model = LinearRegression()

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# shift + tab
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [14]:
# algo 
model.fit(X_train , y_train)

LinearRegression()

In [15]:
model.coef_


array([9423.81532303])

In [16]:
X_test

array([[9.6],
       [4.9],
       [8.2],
       [5.3],
       [3.2],
       [3.7]])

In [17]:
y_pred = model.predict(X_test)

In [18]:
y_pred

array([115790.21011287,  71498.27809463, 102596.86866063,  75267.80422384,
        55477.79204548,  60189.69970699])

In [19]:
112635/115790 * 100

97.27523965800155

In [20]:
# y = c +  wx
# 9449 * 1.1
model.predict([[ 1.1 ]] )

array([35687.77986711])

In [21]:
36187/39343 * 100

91.97824263528454

In [22]:
9449 * 1.1

10393.900000000001

In [23]:
c = model.intercept_

In [24]:
c

25321.583011776813

In [25]:
25792 + 9449 * 1.1

36185.9

In [26]:
import joblib

In [27]:
joblib.dump(model,"sal.pki")

['sal.pki']

In [29]:
model.predict([[2.5]])

array([48881.12131935])